Rulers
pgarneau/apaintus pull request #28
Opened 2019-02-23 02:23 UTC by pspino

Added rulers feature

2019-02-23 04:19 UTC, boscoa commented on src/main/java/apaintus/models/Preference.java
> +	WIDTH, HEIGHT, SAVE_PATH, LOAD_PATH, STROKE_SIZE, STROKE_COLOR, FILL_COLOR, FULLSCREEN,SNAP_GRID
Il te manque l'espace après la virgule

2019-02-23 04:19 UTC, boscoa commented on src/main/java/apaintus/models/Ruler.java
> +package apaintus.models;
Il ne doit pas avoir de javafx dans le package models

2019-02-23 04:19 UTC, boscoa commented on src/main/java/apaintus/controllers/CanvasController.java
> +        snapGrid = new SnapGrid(canvas.getWidth(), canvas.getHeight(),snapGridActive);
Espace après la virgule. Same pour ligne 78 et 82

2019-02-23 15:57 UTC, pspino commented on src/main/java/apaintus/controllers/CanvasController.java
> +        snapGrid = new SnapGrid(canvas.getWidth(), canvas.getHeight(),snapGridActive);
En Theory, il ne devrait pas etre dans le modele, la snapgrid aussi puisque ce sont des UI elements seulement, excepter la positions des points dans le grid

2019-02-23 16:03 UTC, boscoa commented on src/main/java/apaintus/controllers/CanvasController.java
> +        snapGrid = new SnapGrid(canvas.getWidth(), canvas.getHeight(),snapGridActive);
Tu es dans le mauvais commentaire. Si tu n'importes pas un package javafx, ça peut faire partie de models. Sinon, un package UI?

2019-02-23 16:06 UTC, pspino commented on src/main/java/apaintus/controllers/CanvasController.java
> +        snapGrid = new SnapGrid(canvas.getWidth(), canvas.getHeight(),snapGridActive);
je me suis dit la meme chose, mais a quel point on veut un nouveau package UI. en fait je devrais les splitter en 2, soit le controller et le model, mais j'ai comme l'impression que cela va etre tres petit comme classes

2019-02-23 22:06 UTC, pgarneau requested changes

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/controllers/CanvasController.java
> +    private Pane xRule;
widthRuler et heightRuler au lieu?

xRule et yRule ca veut pas dire grand chose

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/controllers/CanvasController.java
> +        snapGrid = new SnapGrid(canvas.getWidth(), canvas.getHeight(),snapGridActive);
votre package "UI" c'est views :P

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/controllers/Controller.java
> +    ;
Remove this extra ";"

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/controllers/CanvasController.java
>  package apaintus.controllers;
ctrl+alt+L svp

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/controllers/ToolBarController.java
> +        ObservableList<Double> gradationValues = FXCollections.observableArrayList(10.0,20.0,40.0);
Pourquoi pas faire ces operations dans le FXML? Ca fait juste rajouter plus de lignes dans le controller

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/controllers/ToolBarController.java
>      public Double getSnapGridSize() {
Update le nom de la methode pour match le nouveau nom de variable

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/controllers/ToolBarController.java
> +        if(preferenceSnapGridGradation != null){
ctrl+alt+L pls

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/models/snapgrid/SnapGrid.java
> +		for (int y = 0; y <= drawingAreaHeight; y+=(gradation)) {
ctrl+alt+L

pourquoi "(gradation)" et pas juste "gradation" ?

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/models/snapgrid/SnapGrid.java
> +	public void setGradation(double size) {
change le parametre de la methode aussi

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/models/snapgrid/SnapGrid.java
> +	public void toggle(boolean active) {
Generalement un toggle switch entre 1 ou l'autre. Toggle serait "isActive = !isActive". setActive te permet de le setter comme tu veux. Jte laisse le choix de ce que tu veux garder

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/views/Ruler.java
> +    public void togleRulers(boolean active) {
typo dans le nom de la fonction (toggleRulers)

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/views/Ruler.java
> +        if(active){
ctrl+alt+L

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/views/Ruler.java
> +    public void togleRulers(boolean active) {
Comme mentionne dans un autre fichier, un toggle est "soit un ou l'autre". La viande de ta methode est bonne, mais juste update la methode a toggle ou setActive

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/controllers/CanvasController.java
> +        snapGrid = new SnapGrid(canvas.getWidth(), canvas.getHeight());
Maybe mettre ce bloc de lignes de code relie au snapGrid et ruler dans une methode pour reduire la pollution de lignes dans le initialize()

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/controllers/CanvasController.java
> +        } catch (NumberFormatException e) {
Si tu vas catch deux types d'exceptions et dealer pareillement avec, tu pourrais toujours faire un seul catch (Exception e)

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/controllers/CanvasController.java
> +        }catch (NullPointerException e){
ctrl+alt+L

2019-02-23 22:06 UTC, pgarneau commented on src/main/java/apaintus/views/Ruler.java
> +    public void resizeUpdate() {
Maybe changer le nom de la methode a "resize()" ?

2019-02-23 22:24 UTC, boscoa commented on src/main/java/apaintus/controllers/Controller.java
> +    ;
Dans ma PR je l'ai fait

2019-02-24 00:12 UTC, pspino commented on src/main/java/apaintus/controllers/CanvasController.java
> +    private Pane xRule;
je lai changer pour xAxisRuler et yAxisRuler a la place. cest pas vraiment le width et le height plus comme la position dans le canvas area

2019-02-24 00:23 UTC, pspino commented on src/main/java/apaintus/controllers/ToolBarController.java
> +        ObservableList<Double> gradationValues = FXCollections.observableArrayList(10.0,20.0,40.0);
en theorie, cest que dans le fxml, cest t'une liste de FXCollection et non tout simplement pas une seule collections, mais bon j'ai fais le changement et ca change pas grand choses.

2019-02-24 00:25 UTC, pspino commented on src/main/java/apaintus/controllers/CanvasController.java
> +        } catch (NumberFormatException e) {
en theorie, on devrait avoir 2 type d'exception, mais un qui ne devrait arrive, soit numberformat, lui faudrait p-e le logger si jamais il arrive ou on log peu importe l'exception.

2019-02-24 00:27 UTC, pspino commented on src/main/java/apaintus/views/Ruler.java
> +    public void resizeUpdate() {
cela pourrait laisser a confusion que l'on resize les rulers et ce n'est pas le cas. Par contre, je ne suis pas contre l'idee du renaming ici. Je verrais plus resizeEventUpdate ?

2019-02-24 00:33 UTC, pgarneau commented on src/main/java/apaintus/views/Ruler.java
> +    public void resizeUpdate() {
C'est plus le principe que resizeUpdate et resizeEventUpdate ca fait pas de sens en anglais. update() serait bon, mais t'as deja une methode qui s'appelle comme ca, donc maybe redraw() ?

2019-02-24 04:36 UTC, pspino commented on src/main/java/apaintus/views/Ruler.java
> +    public void resizeUpdate() {
yea redraw est meilleur, cest plus generique si jamais on veut launcher le tout

2019-02-24 17:37 UTC, boscoa approved these changes

2019-02-24 18:38 UTC, pgarneau approved these changes

2019-02-24 18:39 UTC, merged